<?php

namespace app\models;

use app\core\Model;

class Contacts extends Model
{
    public static $table = SQL_TBL_CONTACTS;

     public static function isContactExists($contact)
    {
        return self::isExists(['contact' => $contact], self::$table);
    }
    public static function edit($data, $where)
    {
        $table = self::$table;
        foreach ($data as $key => $value) {
            if (is_array($value)) {
                $data[$key] = json_encode($value, JSON_UNESCAPED_UNICODE);
            }
        }
        return self::update($data, $where, $table);
    }
    public static function add($data)
    {
        $table = self::$table; 
        foreach ($data as $key => $value) {
            if (is_array($value)) {
                $data[$key] = json_encode($value, JSON_UNESCAPED_UNICODE);
            }
        }
        return self::insert($data, $table);
    }
    public static function remove($cid)
    {
        $table = self::$table;
        return self::delete($cid, $table);
    }
    public static function init(){
        $table = self::$table;
        self::query(
            "CREATE TABLE IF NOT EXISTS $table (
                id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id INT NOT NULL,
                type CHARACTER VARYING(25) NOT NULL DEFAULT '',
                contact CHARACTER VARYING(250) NOT NULL DEFAULT '',
                data JSON DEFAULT NULL,
                created_at TIMESTAMP DEFAULT NOW(),
                updated_at TIMESTAMP DEFAULT NOW(),
                CONSTRAINT fk_user
                    FOREIGN KEY(user_id) 
                    REFERENCES users(id)
                    ON DELETE CASCADE
            );"
        );
    }
}
