<?php

namespace app\models;

use app\core\Model;
use app\core\Locale;

class Games extends Model
{
    public static $gameNames = [
        'mafia' => '{{ Mafia }}',
        'poker' => '{{ Poker }}',
        'board' => '{{ Board }}',
        'cash' => '{{ Cash }}',
        'etc' => '{{ Etc }}'
    ];
    public static $mainTable = SQL_TBL_GAMES;

    public static function menu()
    {
        return [''];
    }
    public static function init()
    {
        $table = self::$mainTable;
        self::query(
            "CREATE TABLE IF NOT EXISTS $table (
                id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                weekid INT NOT NULL DEFAULT '0',
                dayid INT NOT NULL DEFAULT '0',
                win INT NOT NULL DEFAULT '0',
                manager JSON DEFAULT NULL,
                players JSON DEFAULT NULL,
                vars JSON DEFAULT NULL,
                text JSON DEFAULT NULL,
                start JSON DEFAULT NULL,
            );"
        );
    }
}
