<?php

namespace app\models;

use app\core\Model;
use app\core\Locale;

class Games extends Model
{
    public static $gameNames = [];
    public static $defaultGames = [
        'mafia' => 'Mafia',
        'poker' => 'Poker',
        'board' => 'Board',
        'cash' => 'Cash',
        'etc' => 'Etc'
    ];
    public static $table = SQL_TBL_GAMES;

    public static function names(){
        
        if (!empty(self::$gameNames))
            return self::$gameNames;

        $games = Pages::findBy('type', 'game');

        if (!$games)
            return self::$defaultGames;
            
        $count = count($games);
        $names = [];

        for ($i=0; $i < $count; $i++) {
            $names[$games[$i]['slug']] = $games[$i]['title'];
        }
        self::$gameNames = array_merge(self::$defaultGames, $names);

        return self::$gameNames;
    }
    public static function menu()
    {
        $games = Locale::apply(self::names());
        $result = [];
        foreach($games as $game=>$name){
            $result[] =
                [
                    'name' => $name,
                    'short_name' => $game,
                    'fields' => '',
                ];
        }
        return $result;
    }

    public static function create($post){
        $table = self::$table;

        $manager = Users::getDataByName($post['manager']);

        $data = [
            'week_id' => Weeks::currentId(),
            'day_id' => Days::current(),
            'manager' => json_encode([
                'id' => $manager['id'],
                'name' => $manager['name'],
            ], JSON_UNESCAPED_UNICODE),
            'players' => json_encode(Users::assingIds($post['player'], $post['role']), JSON_UNESCAPED_UNICODE),
            'started_at' => $_SERVER['REQUEST_TIME'],
        ];
        return self::insert($data,$table);
    }

    public static function save($post, $id){
        $table = self::$table;
        $data = [
            'state' => $post['state'],
            'prevStates' => $post['prevstates'],
        ];
        self::update($data, ['id' => $id], $table);
    }
    
    public static function init()
    {
        $table = self::$table;
        self::query(
            "CREATE TABLE IF NOT EXISTS $table (
                id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                week_id INT NOT NULL DEFAULT '0',
                day_id INT NOT NULL DEFAULT '0',
                type CHARACTER VARYING(30) NOT NULL DEFAULT 'mafia',
                win INT NOT NULL DEFAULT '0',
                manager JSON DEFAULT NULL,
                players JSON DEFAULT NULL,
                state JSON DEFAULT NULL,
                prevStates JSON DEFAULT NULL,
                started_at INT NOT NULL DEFAULT '0'
            );"
        );
    }
}
