<?php

namespace app\models;

use app\core\Locale;
use app\core\Model;

class Pages extends Model
{
    public static $table = SQL_TBL_PAGES;

    public static function getCount($type='news')
    {
        $table = static::$table;
        return self::query("SELECT COUNT(id) FROM $table WHERE type = ? ", [$type], 'Column');
    }
    public static function getPerPage($page = 0, $type='news')
    {
        $table = static::$table;
        $searchQuery = "SELECT * FROM $table WHERE type = ? ";
        $values = [$type];
        $searchQuery .= ' ORDER BY id DESC';

        if ($page === 0)
            $searchQuery .= ' LIMIT ' . CFG_NEWS_PER_PAGE;
        else
            $searchQuery .= ' LIMIT ' . CFG_NEWS_PER_PAGE . ' OFFSET ' . (CFG_NEWS_PER_PAGE * $page);

        return self::query($searchQuery, $values, 'Assoc');
    }
    public static function create(&$data)
    {
        $array = self::prepDbArray($data);
        $array['slug'] = preg_replace(['/[^a-z0-9]+/i', '/--/'], '-', Locale::translitization(trim($array['title'])));
        return self::insert($array, self::$table);
    }
    public static function edit($data, $id)
    {
        $array = self::prepDbArray($data);
        return self::update($array, ['id' => $id], static::$table);
    }
    public static function prepDbArray($data){
        $array = [
            'title' => trim($data['title']),
            'subtitle' => trim($data['subtitle']),
            'html' => trim($data['html']),
        ];
        if (isset($data['type'])) {
            $array['type'] = trim($data['type']);
        }
        if (isset($data['logo'])) {
            $array['data'] = json_encode(['logo' => $data['logo']], JSON_UNESCAPED_UNICODE);
        }
        return $array;
    }
    public static function remove($id)
    {
        return self::delete($id, static::$table);
    }
    public static function init()
    {
        $table = static::$table;
        self::query(
            "CREATE TABLE IF NOT EXISTS $table (
                id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id INT NOT NULL DEFAULT '1',
                type CHARACTER VARYING(25) NOT NULL DEFAULT '',
                title CHARACTER VARYING(250) NOT NULL DEFAULT '',
                slug CHARACTER VARYING(250) NOT NULL DEFAULT '',
                subtitle CHARACTER VARYING(250) NOT NULL DEFAULT '',
                keywords CHARACTER VARYING(250) NOT NULL DEFAULT '',
                html TEXT NULL DEFAULT NULL,
                data JSON DEFAULT NULL,
                published_at TIMESTAMP DEFAULT NOW(),
                created_at TIMESTAMP DEFAULT NOW(),
                updated_at TIMESTAMP DEFAULT NOW(),
                date_delete INT NOT NULL DEFAULT '0',
                CONSTRAINT fk_user
                    FOREIGN KEY(user_id) 
                    REFERENCES users(id)
                    ON DELETE SET DEFAULT
            );"
        );
        $data = [
            [
                'type' => 'page',
                'title' => 'Домашня сторінка',
                'slug' => 'home',
                'subtitle' => 'Про гру',
                'html' => '<p>Клубна гра Мафія, в класичному стилі вражає свою легкістю та складністю одночасно! Результат кожної гри, завжди залежить не тільки від особистого вкладу кожного окремого гравця, але й від команди в цілому. Так, ми чудово розуміємо, що до цього моменту - нічого нового, для командних видів ігор - не було...</p><p>Але є нюанси!</p><p>Адже, стосовно того, хто знаходиться у твоїй команді - інтрига зберігається до самого закінчення гри! Прокачайте, разом з нами, свої навички логіки, дедукції, емпатії, інтуїції, да й що там казати - телепатії, також!</p><p>Запрошуємо Вас, до нашого дружнього та кмітливого клубу гравців у Мафію!:)</p>',
            ],
            [
                'type' => 'game',
                'title' => 'Мафія',
                'slug' => 'mafia',
                'subtitle' => 'Класична гра мафія',
                'html' => '<p>Клубна гра Мафія, в класичному стилі вражає свою легкістю та складністю одночасно! Результат кожної гри, завжди залежить не тільки від особистого вкладу кожного окремого гравця, але й від команди в цілому. Так, ми чудово розуміємо, що до цього моменту - нічого нового, для командних видів ігор - не було...</p><p>Але є нюанси!</p><p>Адже, стосовно того, хто знаходиться у твоїй команді - інтрига зберігається до самого закінчення гри! Прокачайте, разом з нами, свої навички логіки, дедукції, емпатії, інтуїції, да й що там казати - телепатії, також!</p><p>Запрошуємо Вас, до нашого дружнього та кмітливого клубу гравців у Мафію!:)</p>',
            ],
            [
                'type' => 'promo',
                'title' => 'Записываемся активнее!',
                'slug' => 'mafia',
                'subtitle' => 'Важен каждый игрок!',
                'html' => 'Только Ваше участие позволяет клубу и другим игрокам становиться лучше!',
            ],
        ];
        self::insert($data, $table);
    }
}
